### ISSUE TITLE
Server Crash: ConcurrentModificationException

### ISSUE THREAD

**Issue by RelativeProgramming** [ValhelsiaTeam/Valhelsia-Origins#3]
The Server just crashed, without any player interaction:
Complete Log:
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Origins/files/4962627/latest.log)
Error Message:
```
[22Jul2020 19:13:53.346] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_172]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_172]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:496) ~[server-1.15.2-extra.jar:?]
	at blusunrize.immersiveengineering.common.IESaveData.func_189551_b(IESaveData.java:104) ~[?:?]
	at net.minecraft.world.storage.WorldSavedData.func_215158_a(WorldSavedData.java:44) ~[?:?]
	at net.minecraft.world.storage.DimensionSavedDataManager.func_212775_b(DimensionSavedDataManager.java:125) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_73042_a(ServerWorld.java:761) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:748) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:528) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:804) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
```

**Comment by RelativeProgramming** [comment]
This happened with Version 1.0.2 of the pack. This error occurs shortly after every restart attempt, which makes the server version of the mod pack basically unusable.
